import { DEFAULT_PARAMS, CVSDDelayParams } from '../types';

export const PRESETS: Record<string, CVSDDelayParams> = {
  default: {
    ...DEFAULT_PARAMS,
    circuitType: 'discrete',
    delayTime: 350,
    feedback: 0.6,
    mix: 0.5,
    wobbleRate: 1.5,
    wobbleDepth: 0.5,
    feedbackTone: 4000,
    character: 0,
    dynamicResponse: 0.2,
    stereoSpread: 0.0,
    discrete: { stepSize: 0.02 },
    clockJitter: 0.0,
    integratorLag: 1.0,
  },
  'crunch-overload': {
    ...DEFAULT_PARAMS,
    circuitType: 'discrete',
    delayTime: 280,
    feedback: 0.55,
    mix: 0.6,
    character: 38,
    discrete: { stepSize: 0.005 },
    integratorLag: 12.0,
    clockJitter: 25.0,
    reconstructionCutoff: 2200,
    wobbleRate: 2.5,
    wobbleDepth: 2.0,
    feedbackTone: 3000,
    dynamicResponse: 0.5,
    stereoSpread: 30.0,
  },
  'dark-tape': {
    ...DEFAULT_PARAMS,
    circuitType: 'discrete',
    delayTime: 500,
    feedback: 0.75,
    mix: 0.45,
    character: 12,
    discrete: { stepSize: 0.015 },
    integratorLag: 5.0,
    clockJitter: 15.0,
    reconstructionCutoff: 1200,
    integratorLeak: 0.992,
    wobbleRate: 0.5,
    wobbleDepth: 4.5,
    feedbackTone: 1200,
    dynamicResponse: 0.1,
    stereoSpread: 50.0,
  },
  'one-bit-chaos': {
    ...DEFAULT_PARAMS,
    circuitType: 'discrete',
    delayTime: 180,
    feedback: 0.7,
    mix: 0.65,
    character: 36,
    discrete: { stepSize: 0.05 },
    integratorLag: 1.0,
    clockJitter: 85.0,
    reconstructionCutoff: 4500,
    wobbleRate: 8.0,
    wobbleDepth: 12.0,
    feedbackTone: 8000,
    dynamicResponse: 0.8,
    stereoSpread: 80.0,
  },
  'clean-reference': {
    ...DEFAULT_PARAMS,
    circuitType: 'discrete',
    delayTime: 400,
    feedback: 0.5,
    mix: 0.5,
    character: -12,
    discrete: { stepSize: 0.005 },
    clockJitter: 0.0,
    integratorLag: 1.0,
    reconstructionCutoff: 15000,
    integratorLeak: 0.999,
    wobbleRate: 1.0,
    wobbleDepth: 0.0,
    feedbackTone: 20000,
    dynamicResponse: 1.0,
    stereoSpread: 0.0,
  },
  'vintage-cvsd': {
    ...DEFAULT_PARAMS,
    circuitType: 'companded',
    delayTime: 320,
    feedback: 0.65,
    mix: 0.5,
    character: 15,
    companded: {
      minStepSize: 0.001,
      maxStepSize: 0.15,
      syllabicTime: 12,
    },
    reconstructionCutoff: 3000,
    integratorLeak: 0.99,
    dynamicResponse: 0.0,
    clockJitter: 10.0,
    integratorLag: 1.2,
    wobbleRate: 1.0,
    wobbleDepth: 0.5,
  },
  'reverse-space': {
    ...DEFAULT_PARAMS,
    circuitType: 'discrete',
    delayTime: 400,
    feedback: 0.65,
    mix: 0.6,
    character: 15,
    discrete: { stepSize: 0.015 },
    wobbleRate: 1.2,
    wobbleDepth: 2.5,
    feedbackTone: 3500,
    stereoSpread: 60.0,
    reverseMode: true,
    reverseChunkSize: 450,
    reverseFeedback: false,
  },
  'reverse-granular': {
    ...DEFAULT_PARAMS,
    circuitType: 'discrete',
    delayTime: 250,
    feedback: 0.7,
    mix: 0.65,
    character: 35,
    discrete: { stepSize: 0.03 },
    wobbleRate: 3.5,
    wobbleDepth: 4.0,
    feedbackTone: 5000,
    stereoSpread: 40.0,
    reverseMode: true,
    reverseChunkSize: 85,
    reverseFeedback: true,
  },
};
